version: '3.8'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: pagwaydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d

volumes:
  pgdata: