services:
  postgres:
    image: postgres
    environment:
      TZ: America/Cuiaba
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - app-network

  transactions:
    build: 
      context: .
      dockerfile: ./src/transactions/Dockerfile
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - app-network

  payable:
    build: 
      context: .
      dockerfile: ./src/payable/Dockerfile
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - app-network

  balance:
    build: 
      context: .
      dockerfile: ./src/balance/Dockerfile
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - app-network
  
  users:
    build: 
      context: .
      dockerfile: ./src/users/Dockerfile
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - app-network

  api-gateway:
    build:
      context: .
      dockerfile: ./src/gateway/Dockerfile
    ports:
      - "4000:3000"
    depends_on:
      - rabbitmq
      - transactions
      - payable
      - balance
      - users
    networks:
      - app-network

volumes:
  postgres-data:
  rabbitmq-data:

networks:
  app-network:
